### ISSUE TITLE
image pull error when installed from operator hub

### ISSUE THREAD

**Issue by raffaelespazzoli** [openshift/node-problem-detector-operator#13]
I just installed this operator from operato hub and I'm getting this error:
```
Failed to pull image "openshift/ose-node-problem-detector:v4.0": rpc error: code = Unknown desc = Error reading manifest v4.0 in docker.io/openshift/ose-node-problem-detector: errors: denied: requested access to the resource is denied unauthorized: authentication required
```
on the daemon set image.

**Comment by arunabhabanerjee** [comment]
> I just installed this operator from operato hub and I'm getting this error:
> 
> ```
> Failed to pull image "openshift/ose-node-problem-detector:v4.0": rpc error: code = Unknown desc = Error reading manifest v4.0 in docker.io/openshift/ose-node-problem-detector: errors: denied: requested access to the resource is denied unauthorized: authentication required
> ```
> 
> on the daemon set image.

Are you able to solve this issue? I am facing the same problem.

> Failed to pull image "openshift/ose-node-problem-detector:v4.0": rpc error: code = Unknown desc = Error reading manifest v4.0 in docker.io/openshift/ose-node-problem-detector: errors: denied: requested access to the resource is denied unauthorized: authentication required

**Comment by mohit-sheth** [comment]
@raffaelespazzoli  @arunabhabanerjee 
did anyone of you find a solution?

**Comment by east4ming** [comment]
I have the same problem.

**Comment by east4ming** [comment]
Should be "registry.svc.ci.openshift.org/openshift/ose-node-problem-detector:v4.0" ?

**Comment by arunabhabanerjee** [comment]
Still I am facing the same issue.

`Failed to pull image "registry.svc.ci.openshift.org/openshift/origin-v4.0:node-problem-detector-operator": rpc error: code = Unknown desc = Error reading manifest node-problem-detector-operator in registry.svc.ci.openshift.org/openshift/origin-v4.0: received unexpected HTTP status: 500 Internal Server Error`
