### ISSUE TITLE
image not pullable

### ISSUE THREAD

**Issue by davidkarlsen** [openshift/node-problem-detector-operator#27]
latest version of operator uses an invalid image:
```
Back-off pulling image "registry.svc.ci.openshift.org/openshift/origin-v4.0:node-problem-detector-operator"
```

```
docker pull registry.svc.ci.openshift.org/openshift/origin-v4.0:node-problem-detector-operator
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
```

**Comment by sirwalrus** [comment]
+1, I assume this container should be available on quay.io instead of registry.svc.ci.openshift.org

**Comment by vrutkovs** [comment]
Use `registry.ci.openshift.org/origin/4.7:node-problem-detector-operator` or `quay.io/openshift/origin-node-problem-detector-operator:4.7`

**Comment by davidkarlsen** [comment]
/remove-lifecycle rotten
/lifecycle frozen
@vrutkovs where do I set that? But shouldn't that be the operator default?

**Comment by vrutkovs** [comment]
> where do I set that? But shouldn't that be the operator default?

Operator takes it from the payload. If you need to fetch it for experiments use Quay pullspec

/close
